name: anyminutenow
on:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/5f85939589ef6708af9ead2d"
